# Generated by Django 4.0.10 on 2023-11-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=280, unique=True)),
                ('username', models.CharField(max_length=300)),
                ('encrypted_password', models.CharField(max_length=120)),
            ],
        ),
    ]
