# Generated by Django 4.0.10 on 2023-11-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idearest04app', '0002_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idearest04app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idearest04app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1400)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idearest04app.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idearest04app.customuser')),
            ],
        ),
    ]
